Added lab9
csatuic/cs361-website-old pull request #30
Opened 2021-03-12 15:59 UTC by MetalChair

2021-03-12 19:08 UTC, shubhams requested changes

2021-03-12 19:08 UTC, shubhams commented on _labs/lab9.md
> +title: week 11 lab
week 10* lab

2021-03-12 19:08 UTC, shubhams commented on _labs/lab9.md
> +1.  We give you two programs to use to test the code you write in `hw4.c`, `main_debug.c` and `main.c`.
`main_debug.c` -> `hw4-library/main_debug.c`

2021-03-12 19:08 UTC, shubhams commented on _labs/lab9.md
> +2.  `debug_main.c` has a simple method to test if your code is working.
`main_debug.c` -> `hw4-library/main_debug.c`

2021-03-12 19:08 UTC, shubhams commented on _labs/lab9.md
> +5.  Answer the Gradescope question on `my_malloc`.
I couldn't see the assignment on gradescope

2021-03-12 19:08 UTC, shubhams commented on _labs/lab9.md
> +2.  `debug_main.c` has a simple method to test if your code is working.
on second thought, i think `debug_main.c` should be in the root dir of the hw4 folder, right?

2021-03-12 19:08 UTC, shubhams commented on _labs/lab9.md
> +4.  This code allocates 1000 pointers, and then deallocates them all and
Do we need to tell the students how to use `debug_main.c`.
I get a seg fault when i use the same recipe as `hw4` in the Makefile and I replace it `main.c` with `debug_main.c`.

2021-03-12 19:08 UTC, shubhams commented on _labs/lab9.md
> +3.  Answer the question on `main.c` on Gradescope.
again, i couldn't find no gradescope assignment

2021-03-12 19:08 UTC, shubhams commented on _labs/lab9.md
> +## Functions You Will Write
I think this section could be moved to the end of the write up, after `## Total grade calculation`

2021-03-12 19:11 UTC, moebit commented on _labs/lab9.md
> +2.  `debug_main.c` has a simple method to test if your code is working.
it's fine if it's in the `hw4-library`, we just need to make sure it compiles correctly

2021-03-12 19:16 UTC, moebit commented on _labs/lab9.md
> +date: 2021-15-03
throws a date format error. change it to 2021-03-15

2021-03-12 21:35 UTC, MetalChair commented on _labs/lab9.md
> +2.  `debug_main.c` has a simple method to test if your code is working.
I added a section to the write-up explaining how to setup debug_main and the makefile. Take a look and let me know if this is sufficient

2021-03-12 21:35 UTC, MetalChair commented on _labs/lab9.md
> +5.  Answer the Gradescope question on `my_malloc`.
Created, thanks @moebit

2021-03-13 00:14 UTC, moebit commented on _labs/lab9.md
> +4.  This code allocates 1000 pointers, and then deallocates them all and
@MetalChair please add `make` in front of ``` so the syntax would look nicer and mention that the space should be one tab for the correct formatting. replace the double quotes with ticks (`hw4.h` instead of "hw4.h")

2021-03-15 03:57 UTC, merged